# Generated by Django 4.2.4 on 2023-10-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sesseoin_id',
            new_name='sesseion_id',
        ),
    ]
