# Generated by Django 4.2.4 on 2023-10-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_sesseion_id_student_sesseion_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sesseion_year_id',
            new_name='session_year_id',
        ),
    ]
